### ISSUE TITLE
Bug report: Modo offline queda entrampado en la cola de pull list

### ISSUE THREAD

**Issue by Yiakman** [Cotalker/documentation#806]
### Affected system

Cotalker Web Application, Cotalker Android Application, Cotalker iOS Application

### Affected environment

Production

### App version

17.8.4

### Details

Modo offline

### Steps to reproduce

1. Ingresar con cuenta (PEDIR A GONZUARDO***)
2. Revisar sincronización hasta que deje de actualizarse (unos 5 minutos me bastó a mi para tener el debug data)
3. Abrir debug data para constatar atasco

### Expected result

Cola pueda resolver la petición de los surveymessages, cola Pull List pueda seguir ejecutando

### Additional data

Debug data modo offline

```JSON
[
  {
    "id": 5,
    "createdAt": "2022-03-30T03:14:11.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": "2022-03-30T03:16:43.348Z",
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 2,
      "acceptedRetries": 0,
      "debugData": {
        "state": "unknown-error",
        "data": {
          "message": "sqlite3_prepare_v2 failure: unrecognized token: \"$\"",
          "code": 5,
          "name": "QueryFailedError",
          "query": "SELECT \"$\".\"_id\" AS \"$__id\", \"$\".\"survey\" AS \"$_survey\", \"$\".\"order\" AS \"$_order\", \"$\".\"sender\" AS \"$_sender\", \"$\".\"contentType\" AS \"$_contentType\", \"$\".\"content\" AS \"$_content\", \"$\".\"isActive\" AS \"$_isActive\", \"$\".\"contentArray\" AS \"$_contentArray\", \"$\".\"createdAt\" AS \"$_createdAt\", \"$\".\"modifiedAt\" AS \"$_modifiedAt\" FROM \"survey_message\" \"$\" WHERE $._id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
          "parameters": [
            "621db61d7b5a1a1b6494be52",
            "621db61d7b5a1a13a294be51",
            "621db61d7b5a1a617d94be50",
            "621db61d7b5a1a177194be53",
            "621db61d7b5a1ae86094be55",
            "621db61d7b5a1a138594be54",
            "621db61d7b5a1a6ceb94be56",
            "621db61d7b5a1a703b94be58",
            "621db61d7b5a1a336094be59",
            "621db61d7b5a1a5f4e94be5a",
            "621db61d7b5a1a4f7094be57",
            "621db61d7b5a1a854c94be5e",
            "621db61d7b5a1a278b94be5b",
            "621db61d7b5a1ac3ea94be5c",
            "621db61d7b5a1a70c594be5f",
            "621db61d7b5a1a85da94be5d",
            "621db61d7b5a1ae4c294be61",
            "621db61d7b5a1a94b994be62",
            "621db61d7b5a1ad54f94be63",
            "621db61d7b5a1a37d094be60",
            "621db61d7b5a1a7f0a94be64",
            "621db61d7b5a1a5c0b94be67",
            "621db61d7b5a1a09d294be6a",
            "621db61d7b5a1a1cb694be69",
            "621db61d7b5a1a47a694be66",
            "621db61d7b5a1a362994be68",
            "621db61d7b5a1a72ed94be65",
            "621db61d7b5a1a499294be6b",
            "621db61d7b5a1a618994be6e",
            "621db61d7b5a1a69e194be6f",
            "621db61d7b5a1ada8494be6d",
            "621db61d7b5a1a8b8694be6c",
            "621db61d7b5a1a390794be71",
            "621db61d7b5a1a28d194be70",
            "621db61d7b5a1a404d94be72",
            "621db61d7b5a1a8e8c94be73",
            "621db61d7b5a1a4a8594be74",
            "621db61d7b5a1a53a494be76",
            "621db61d7b5a1a23a894be75",
            "621db61d7b5a1a10e794be79",
            "621db61d7b5a1a44d494be77",
            "621db61d7b5a1ae11a94be78",
            "621db61d7b5a1a706294be7a",
            "62337f6e5908ae0007176953",
            "62337f6e5908ae0007176956",
            "6233920180467d000750bc9c",
            "6233920180467d000750bc9f",
            "623205b164ae6a0007727b00",
            "6232aaa080467d00074dfc25",
            "6232611a7ec93e0007140242",
            "622204638d6c9d00087aba59",
            "622146078d6c9d00087a8438",
            "6232ba0980467d00074e2270",
            "623d51cb6e9fd30007b2d14a",
            "623d50b37252090007d98a50",
            "623d50b37252090007d98a53",
            "62298ae502bc480007ca8399",
            "62298ae502bc480007ca839c",
            "62298ae502bc480007ca839f",
            "6232453f7ec93e00071359c5",
            "62298ae502bc480007ca83a2",
            "622a9f599a14a8000740445c",
            "62298dbc02bc480007ca8512",
            "622a9f599a14a8000740445f",
            "623bf6302d2c800007f060e3",
            "62298dbc02bc480007ca8514",
            "62298dbc02bc480007ca8516",
            "62298dbc02bc480007ca8518",
            "62298dbc02bc480007ca851b",
            "62298dbc02bc480007ca851e"
          ],
          "stack": "QueryFailedError: sqlite3_prepare_v2 failure: unrecognized token: \"$\"\n    at new w (http://localhost/main.453d43ffe8fa8d384597.js:1:2495440)\n    at http://localhost/main.453d43ffe8fa8d384597.js:1:2598147\n    at myerror (http://localhost/login:3120:16)\n    at SQLitePluginTransaction.handleStatementFailure (http://localhost/login:3265:9)\n    at Object.error (http://localhost/login:3286:18)\n    at mycb (http://localhost/login:3328:20)\n    at Object.callbackFromNative (http://localhost/login:1360:52)\n    at <anonymous>:1:9"
        }
      }
    },
    "body": {
      "syncable": "survey",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 6,
    "createdAt": "2022-03-30T03:14:11.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "company",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 7,
    "createdAt": "2022-03-30T03:14:11.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "local-files",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 8,
    "createdAt": "2022-03-30T03:14:12.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "message",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 9,
    "createdAt": "2022-03-30T03:14:12.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "task",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 10,
    "createdAt": "2022-03-30T03:14:12.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "sm-state",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 11,
    "createdAt": "2022-03-30T03:14:18.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "property",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 12,
    "createdAt": "2022-03-30T03:19:04.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "channel",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 13,
    "createdAt": "2022-03-30T03:19:04.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "group",
      "syncableAction": "pull",
      "data": null
    }
  },
  {
    "id": 14,
    "createdAt": "2022-03-30T03:19:04.000Z",
    "queue": "pulls",
    "debug": {
      "lastExecutionIntent": null,
      "serverErrorRetries": 0,
      "networkErrorRetries": 0,
      "unknownErrorRetries": 0,
      "acceptedRetries": 0,
      "debugData": null
    },
    "body": {
      "syncable": "user",
      "syncableAction": "pull",
      "data": null
    }
  }
]

```

**Comment by agallardol** [comment]
Done, estará resuelto en 17.8.5
